apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-engine
  namespace: bzinga
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 1000
  selector:
    matchLabels:
      app: game-engine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: game-engine
    spec:
      containers:
        - env:
            - name: ENV
              value: DEV
            - name: MODE
              value: SERVER
            - name: PORT
              value: "80"

            - name: storage_account_name
              value: bzdevstorageaccount
            - name: container_name
              value: game-engine
            - name: connection_string
              valueFrom:
                secretKeyRef:
                  name: azure-blob
                  key: connection_string
                  optional: false
            - name: storage_account_key
              valueFrom:
                secretKeyRef:
                  name: azure-blob
                  key: storage_account_key
                  optional: true

          name: game-engine
          image: bzinfdevqacr.azurecr.io/game-engine:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: external
              protocol: TCP
          resources:
            limits:
              cpu: 2300m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 756Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30