apiVersion: v1
kind: Service
metadata:
  labels:
    app: game-engine-sync
  name: game-engine-sync
  namespace: bzinga
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.09.02
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 80
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: game-engine-sync
  sessionAffinity: None
  type: LoadBalancer