apiVersion: v1
kind: Service
metadata:
  labels:
    app: game-engine
  name: game-engine
  namespace: bzinga
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.161.161
  clusterIPs:
    - 10.0.160.16
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: https
      #      nodePort: 32036
      port: 443
      protocol: TCP
      targetPort: 80
    - name: http
      #      nodePort: 32037
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: game-engine
  sessionAffinity: None
  type: LoadBalancer